### ISSUE TITLE
Problema 4

### ISSUE THREAD

**Issue by ghost** [AsLogd/Problemes-Ampliaci-Algorismia#12]
Mi propuesta para el apartado (a)

![sin titulo](https://user-images.githubusercontent.com/10214431/41233517-f4555b38-6d89-11e8-99ef-af41ec5c0d53.png)

**Comment by josepdecid** [comment]
Jo ho he formalitzat com un problema de maximització en ILP:

![screen shot 2018-06-11 at 18 07 25](https://user-images.githubusercontent.com/11754473/41243516-9f584eec-6da2-11e8-988f-bf6673d57f6d.png)

**Comment by josepdecid** [comment]
Hi ha una cosa que no acabo de veure clar, tenint en compte que divideixes pel pes de tots els vèrtexs, aquest valor és constant i no afecta en res dividir-ho o no oi?

**Comment by ghost** [comment]
Per formalitzar no sé si es pot treure, però a efectes pràctics no aporta res.

**Comment by gonsp** [comment]
Alguna idea para el apartado b)? Parece chungo

**Comment by ghost** [comment]
El problema parece ser un weigthed independent set nuevamente. Mi duda es si podemos construir la tree decomposition y poner esta complejidad de construcción en el factor dependiente del tw.

Si se puede he encontrado una posible solución: http://neeldhara.com/ASPAK2014/content/notes/SlidesDPOverTreewidth.pdf

**Comment by gonsp** [comment]
Por qué dices nuevamente? El ej 3 va de weighted set cover

**Comment by ghost** [comment]
@GonMolon Tienes razón. Cómo ves tema construir tree decomposition?

**Comment by Dexutar** [comment]
http://www.win.tue.nl/~jnederlo/2MMD30/lecturenotes/L7/L7.pdf

El 4 b) es aixo basicament. Pagina 4 :)

**Comment by Urigueler** [comment]
Ho explica bastant bè però no acabo d'entendre com manega la segona coordenada de la taula amb el subset Y... Osigui no se com interpretar-ho.

**Comment by AsLogd** [comment]
Una cosa. Com ho fareu per explicar el apartat b? El algorisme es força complex, posar totes les regles i tal seria com molt farragos, no?

**Comment by gonsp** [comment]
No creo que quede alternativa...

**Comment by AsLogd** [comment]
Ya, esque habiamos pensado que igual justificarlo de alguna forma rollo... 'a la tree decomposition tenim totes les combinacions de vertexos que son connexos (i per tant no poden treballar junts) i podem visitarles totes en 2^k n^O(1)...'. No crees que seria factible algo de este rollo?

**Comment by DavidMoranPomes** [comment]
He recogido todo lo que habéis dicho y lo he puesto en un [pdf](https://github.com/AsLogd/Problemes-Ampliaci-Algorismia/files/2097914/Examen_4.pdf), incluida la resolución utilitzando la nice tree decomposition con la notación utilizada en clase. Revisadlo porfa por si se me ha pasado algo.

**Comment by DavidMoranPomes** [comment]
Para la formalización me he basado en la idea de @JosepRivaille , pero vigilad que la formulación que presenta él no es lineal! Las varaibles que quieres computar no pueden aparecer multiplicandose en un problema de programación lineal ^^'

**Comment by gonsp** [comment]
Muy cierto eso! ^

**Comment by AsLogd** [comment]
Ostras no lo sabia. Luego reviso. Gracias!

**Comment by cclaverol** [comment]
En la formalització del problema no es podria eliminar la variable e_i,j i fer:
x_i + x_j ≤ 1  ∀ ( v_i , v_j ) ∈ E
?

**Comment by AsLogd** [comment]
@DavidMoranPomes encara no ho he mirat amb molt deteniment, pero esta molt be. S'enten molt millor que del pdf. Gracies!

**Comment by DavidMoranPomes** [comment]
@cclaverol acabo de rellegir el que has dit, i ho acabo d'entendre que al movil no es veia bé. Ara ho aplico i ho [repujo](https://github.com/AsLogd/Problemes-Ampliaci-Algorismia/files/2099938/Examen_4.pdf).
